exclude: '^(\\.git/|\\.idea/|.*cache.*/|.*migrations/)'

repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.5.0'
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: pretty-format-json
        args: ["--autofix", "--indent=2", "--no-sort-keys"]

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)
        language_version: python3.11

-   repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
    -   id: autoflake
        args: [--remove-all-unused-imports, --in-place]

-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.10.0
    hooks:
    -   id: black

-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-pyproject]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.6.1'
    hooks:
    -   id: mypy
